### ISSUE TITLE
In game tutorial

### ISSUE THREAD

**Issue by elinicksic** [thebclickteam/bocracy#104]
Adding an in game tutorial would be a good idea.

**Comment by ghost** [comment]
I have thought of this idea before, but thought it would be too hard. But now I thought of a new idea to make it work better: using css’s `outline` property to emphasize the element to be interacted with.

**Comment by ethanchoo** [comment]
But in my opinion, the game so far is too simple to really have an effective tutorial.

**Comment by ghost** [comment]
But still, it might be good to have. We’ll see

**Comment by ghost** [comment]
This issue is now #183.
