### ISSUE TITLE
Make game over play again button be dark red

### ISSUE THREAD

**Issue by elinicksic** [thebclickteam/bocracy#106]
The victory is dark green and it blends so this would look better too.

**Comment by ghost** [comment]
This is a really simple one to do and it is a good idea.

**Comment by xutopia** [comment]
Hi, I'm looking to contribute to OSS and I found this issue. Mind if I take it? Also, to which branch should I make the PR? Thanks!

**Comment by ghost** [comment]
Hi @xutopia! I would love for you to take this issue! Thanks for contributing!

Making the pr under the `issue-106` branch would be most appreciative.

Thanks!  Sorry for the uncommented code.

**Comment by xutopia** [comment]
Hey @CameronSamuels, my pleasure! Thank you for the opportunity :)

I don't believe the repo has an `issue-106` branch for me to compare my PR to? Unless you want me to create PR to merge with `master` branch? Let me know which branch you want me to compare my changes to!

**Comment by ghost** [comment]
Oh yes. Sorry. Compare to the `master` branch. I thought you meant what to call the dev branch. Sorry for the dilemma.

**Comment by ghost** [comment]
This is now in pr #107
