### ISSUE TITLE
Update Siren A Character

### ISSUE THREAD

**Issue by ghost** [thebclickteam/bocracy#108]
@ethanchoo, you made a new Siren A image. Was this meant for the current Siren A, or the future upgrade for it.

![siren](https://user-images.githubusercontent.com/25394678/32864086-63ac1266-ca23-11e7-90d7-ff5227517471.png)

I think this new image should be the current Siren A and then we can make a different image for the Dark Siren A (the upgrade).

How about that?

**Comment by ghost** [comment]
Also @ethanchoo, I think that we should remove the curved lines that represent sound waves. IF we remove them, I think it looks nicer.

First, the image won't be animated so the sound waves will not move and it will be unrealistic.

Second, it gets in the way of the character.

Third, I think it is too much in the image and doesn't look good.

I can remove the sound waves myself if you want.

**Comment by ethanchoo** [comment]
Sure, you could remove the sound waves. I just intended it to only really be in the image I put with a few other characters, and not the actual game.

**Comment by ghost** [comment]
Oh, I completely understand as you’ve done that before. So ok, I’ll remove it.

**Comment by ghost** [comment]
I think that the A is too wide an looks very bad in the series mode selector. I can remove/shrink some of the parts of the image to make it look way better.
