### ISSUE TITLE
Character upgrades

### ISSUE THREAD

**Issue by ghost** [thebclickteam/bocracy#157]
**Vision**: Upgrades could be unlocked in the store by paying redbacks. The user can upgrade any of the 3 stats (attack, health, healing, and maybe more in the future such as earnings or auto clicks). The price will go up every time the user upgrades. There will be a max of something many upgrades (maybe 5). The upgrades do not change the appearance of the character, just the stats.

Adding upgrades to unlock in the store will be great because:
- The user can improve the characters (something to do after unlocking everything)
- Another way to motivate people to play
- It goes in the empty space in the store (something has to go there and this is the best option)

What do you think?

**Comment by VishwamR** [comment]
We could have character levels where if they lvl up they get exp points that can be used to level up stats. Bosses could drop more exp points than average enemies.

**Comment by VishwamR** [comment]
We should add that in later after the game is bigger.

**Comment by ghost** [comment]
@VishwamR, you mean something like redbacks but instead, it will upgrade characters and not unlock characters? That would be cool.

Maybe instead of creating a secondary currency (which would not be able to be bought in an in-app purchase, so there would be no purpose), we create the EXP like you said.

I will get this approved with @ethanchoo and @lexkilpatrick first, just like most of the stuff we do.

Great! Thanks!

**Comment by VishwamR** [comment]
Maybe we should still keep the secondary currency for stronger characters

**Comment by ghost** [comment]
I will add upgrades to b-Ocracy before it releases. They will be bought using redbacks and will upgrade the 3 stats.

Be aware that I will add the upgrades to be unlocked using the secondary currency and experience later on after the game releases. This is just for now.

**Comment by ghost** [comment]
I have finished these changes and it looks fabulous! I will push the changes to GitHub later this evening.
