### ISSUE TITLE
Disallow search engine indexing of certain pages

### ISSUE THREAD

**Issue by ghost** [thebclickteam/bocracy#158]
Pages such as the battle, multiplayer, endless, and the store shouldn't be indexed on search engines. This can be done with a `robots.txt` file.

Something like this should be good:

```
User-agent: *
Disallow: /battle
Disallow: /multiplayer
Disallow: /endless
Disallow: /store
```

**Comment by VishwamR** [comment]
Random thought but shouldn't we change the symbol on the redbacks. Dollar
bills are used everywhere in the US so maybe we should put something else on them, like something b-Ocracy related.

**Comment by VishwamR** [comment]
Symbol not still

**Comment by VishwamR** [comment]
Something B-Ocracy related

**Comment by ghost** [comment]
Great idea, I never really thought of that. We can look into finding something unique, but this will be low priority. I will create an issue for this.

Also, you can always contact me somehow else instead of commenting on an issue. For this specific question, you could've also created an issue yourself.

**Comment by VishwamR** [comment]
K
