### ISSUE TITLE
Aonarchy series mode B's not attacking

### ISSUE THREAD

**Issue by CooperLan** [thebclickteam/bocracy#16]
On series mode in Aonarchy, the B's are not attacking.

**Comment by ghost** [comment]
I can't seem to reproduce this problem. See the attached GIF animation of the screen recording.

![screen recording GIF animation file](https://user-images.githubusercontent.com/25394678/28297847-b1bce84c-6b35-11e7-97ed-fbcc13eb16cd.gif)

### Can you give me moe information including the following:
- Does it work on non series mode?
- Does it work on other battlegrounds?

### Also, comment with a screen recording of the problem.

*Specs*: I played series mode with 2 characters (goblin horde & archer), on an iPhone SE running iOS 11 using the b-Ocracy iPhone app v1.2.0.

**Comment by CooperLan** [comment]
Working now

**Comment by ghost** [comment]
Good!
