### ISSUE TITLE
Update redbacks icon

### ISSUE THREAD

**Issue by ghost** [thebclickteam/bocracy#163]
Like @VishwamR said, we should remove the $ symbol from the redbacks icon and make it something else b-Ocracy related.

**Comment by VishwamR** [comment]
I have a prototype ready I'll show it to you tomorrow

**Comment by ghost** [comment]
I will add this to the game now! Thanks, @VishwamR!!

**Comment by VishwamR** [comment]
Can you tell me when they're in thx

>
