### ISSUE TITLE
Bosses

### ISSUE THREAD

**Issue by VishwamR** [thebclickteam/bocracy#164]
Since I have nothing to do in this major update I'll start working on the next one for boss fights

**Comment by VishwamR** [comment]
For graphics people only

**Comment by VishwamR** [comment]
Can each Designer take one boss? I'll do Eora

**Comment by ghost** [comment]
The bosses will be added in a future update like you said. And just to say, you are contributing a lot, unlike what you though. So you are being a great help.

### How bosses will work
I like the idea of them being different characters than the normal characters. So yes, you can design the ones you prefer and show them to me.

I also think that we should not have it be "Eora Boss" or "Aonarchy Boss" etc. I think it should be a different battleground (we have already started to put some on [the map](https://git.io/vblMn)).

So I think these could be the names of the cities:
- Aonarchy: Abossicus
- Ammunist: Ascow
- Eora: TBD
- Alinar: TBD
- Alief: TBD

### Checklist
- [ ] Design battle backgrounds
- [ ] Design boss characters
- [ ] Implement them into the game

**Comment by VishwamR** [comment]
I'm calling the Eora boss the Eoran Mud Monster

**Comment by ghost** [comment]
Cool name

**Comment by stonejess** [comment]
Should we have a robot mech B? If so I have that undercover

**Comment by DatDopeGamer** [comment]
By the way, this is stone, ur intern

**Comment by ghost** [comment]
Yes, we will add a robot mech B, @DatDopeGamer. I think we may already have one made by @ethanchoo but not in the game yet. Sorry.

If you want to do something else, you can either create issues on GitHub for ideas or bugs, or you can still design other things. But if you want, you can upload your robot mech to this issue for us to see, and maybe we could use it.

Thanks!

**Comment by stonejess** [comment]
No problem, I have various ideas and I am reviewing them to see if they are possible. I will try and share the ideas as soon as possible.

**Comment by ghost** [comment]
Ok, sounds good!

**Comment by ethanchoo** [comment]
The boss idea is quite interesting, however I am running out of ideas for unique bosses in the game, so maybe you could share some ideas that you have.

**Comment by ghost** [comment]
@VishwamR, any ideas to tell @ethanchoo?

**Comment by VishwamR** [comment]
Try taking the theme of each region and create a sort of beast reflecting
on it

**Comment by ghost** [comment]
For a future game
