### ISSUE TITLE
Update Alief plains battle background

### ISSUE THREAD

**Issue by ethanchoo** [thebclickteam/bocracy#17]
The current background has a dinosaur footprint that shouldn't be there because it isn't in Dinotera.

We could update it by adding clouds or buildings.

**Comment by ghost** [comment]
This is good to do. Send me the updated version once you complete it.

**Comment by ethanchoo** [comment]
![img_1372](https://user-images.githubusercontent.com/30300679/28399205-506dd162-6cd1-11e7-879e-f4cb770c2a7f.JPG)


Do you think this is fine?
There probably needs to be more to fill the actual hills...

**Comment by ghost** [comment]
Fantastic! I will assign this issue to me and add it to the game tommorow.

**Comment by ghost** [comment]
Looks great, Ethan!

**Comment by ghost** [comment]
It is in the game now! Great job @ethanchoo!!
