### ISSUE TITLE
Add Stone to the team

### ISSUE THREAD

**Issue by stonejess** [thebclickteam/bocracy#176]
I noticed I have not been added to the team at the front page. Can you please add me?

Thanks, stone

**Comment by ghost** [comment]
I will add you soon, but for now, I'll wait. You are doing a great job. The reason I am waiting is because I need to get you approved by the COO at the company.

**Comment by stonejess** [comment]
👌🏻

**Comment by ghost** [comment]
@DatDopeGamer, I have now gotten your hiring approved by the COO of the company. You are officially in. I will text you for the final actions. Congrats! 🎉
