### ISSUE TITLE
Combine with the bocracy-ios repo

### ISSUE THREAD

**Issue by ghost** [thebclickteam/bocracy#182]
We can create an orphan branch on this repo for the iOS app instead of having multiple repos for b-Ocracy.

This is good because:
- Less repos
- More together and organized
- No need to switch between 2 different repos
- No need to clone 2 repos to your computer
- Less to manage
- Issues and pr's can be together
- Less times having to add the same collaborators to repos

**Comment by benz-le** [comment]
Yes, this is a good point you have. Would we have to import everything from this repo to the ios repo?

**Comment by ghost** [comment]
We will add the bocracy-ios code to THIS repo. We will put it on an orphan branch called `master-ios`. This can't be done by anyone except us, due to git (we are not merging a branch, we are creating a branch that will always stay, so you can't create a pr for this, therefore you can't do it). Sorry.

**Comment by ghost** [comment]
@Nova281, you can always help on another issue.

**Comment by benz-le** [comment]
Ok
