### ISSUE TITLE
In-game tutorial

### ISSUE THREAD

**Issue by benz-le** [thebclickteam/bocracy#183]
We could add a tab or any way to create instructions for the game. This will make it easier for newcomers to the game.

### @cameronsamuels's edit:
There will be a "Tutorial A" (waiting for a better name) that guides the player on how to play during their first few steps.

**Comment by VishwamR** [comment]
That's a good idea.

>

**Comment by benz-le** [comment]
An in-game tutorial would be fine as well except takes more time which works better.

**Comment by ghost** [comment]
An in game tutorial does take more time but it would be more beneficial (every one will be doing it and understand). @Dolphinbob has already created an issue (#104) about an in-game tutorial.

Is an in game tutorial fine, @Nova281, & @VishwamR?

**Comment by benz-le** [comment]
For now, there could be instructions to the game.

**Comment by ghost** [comment]
Well they're already in the App Store description where people will download the app.

**Comment by VishwamR** [comment]
We could add in a tutorial A that teaches you how it all works

**Comment by benz-le** [comment]
Ok understood then

**Comment by benz-le** [comment]
Agree with Vishwam

**Comment by VishwamR** [comment]
I guess I'll start designing

**Comment by ghost** [comment]
That was also my idea, add a character that guides you playing. Thanks, @VishwamR, and @Nova281 for the thinking.

I will close the other issue (#104) and mark it as a duplicate because this has more information.

@VishwamR, yes you can design a tutorial A if you insist. @ethanchoo might think of a better name.
