### ISSUE TITLE
Holiday Season Events

### ISSUE THREAD

**Issue by stonejess** [thebclickteam/bocracy#184]
I like that our deadline in on Christmas. It’s like a perfect Christmas present! 

Also, we could add a present that you can get for free, and if you want more you can buy them with gems/ other.

**Comment by ghost** [comment]
That would be cool but this would be for next year due to the time we have.

Thanks for the idea!

**Comment by VishwamR** [comment]
> We're releasing on Christmas

Good idea for holiday events.

**Comment by stonejess** [comment]
Ok thanks!
