### ISSUE TITLE
Round the stat values in the store

### ISSUE THREAD

**Issue by elinicksic** [thebclickteam/bocracy#193]
The stats sometimes process with a slightly off precision like in the screenshot. This needs to be fixed.

![3cbb1426-00d8-4fdf-b40d-cc76064238a0](https://user-images.githubusercontent.com/32620307/34180530-a1ccd15e-e4d4-11e7-9bb0-5081710c32be.png)

**Comment by ghost** [comment]
Thanks so much. That is horrible. This is a simple fix and I’ll make sure to fix it soon.

**Comment by VishwamR** [comment]
Umm it happened again

**Comment by VishwamR** [comment]
Umm it happened again

**Comment by VishwamR** [comment]
Idk how you attach a screenshot but I'll show it to Cameron

**Comment by ghost** [comment]
Well are you using the iOS app? If so, the iOS app hasn't been updated to fix this issue. If you are using bocracy.com, then maybe it is a cache problem. This just gave me a reminder to purge the cache so the updates are for sure going to show.

**Comment by VishwamR** [comment]
Reopened for ios

**Comment by VishwamR** [comment]
Reopened for ios

**Comment by ghost** [comment]
@VishwamR, you are saying you were using the iOS app?

**Comment by VishwamR** [comment]
Yup
