### ISSUE TITLE
Show the amount of redbacks the user has

### ISSUE THREAD

**Issue by elinicksic** [thebclickteam/bocracy#196]
You can’t see how many redbacks you have.

**Comment by ghost** [comment]
This is something I was going to do. Thanks for creating an issue for it.

**Comment by VishwamR** [comment]
Are we going to keep it so that you can see how many you have on the main screen or in the store

**Comment by ghost** [comment]
@VishwamR, just in the store. Do you think it should also be somewhere else?

**Comment by VishwamR** [comment]
No I was just wondering
