### ISSUE TITLE
Android app not working on old devices

### ISSUE THREAD

**Issue by CooperLan** [thebclickteam/bocracy#2]
Small words. Style not working. Margins and floating messed up

**Comment by ghost** [comment]
Thanks for this issue post.

I can fix this by assigning a higher minimum API. I believe the current API is 16, and I will make it higher to fix the issue.

I might also find a way to make the webview with webkit all the time.

**Comment by ghost** [comment]
B-Ocracy doesn't work on my Android phone also and it's not even half a year old. The main menu works fine, but once you click anything it comes to a blank solid red screen.

**Comment by ghost** [comment]
On the android phones I tested, it works fine.

**Comment by ghost** [comment]
I will work on this issue whenever the Android app is ready to be worked on.

**Comment by ghost** [comment]
Not working on my phone. Screen still is blank.
