### ISSUE TITLE
iOS app progress resetting

### ISSUE THREAD

**Issue by stonejess** [thebclickteam/bocracy#204]
When I tested the app, I had to get off for a while. When I came back, I had zero Redbacks and all of the characters I bought became locked. I think this might make users rage.

**Comment by stonejess** [comment]
*get off

**Comment by ghost** [comment]
I agree. This could possibly be from something I've seen before in other iOS app's I've made. I thought I fixed the problem, but I can look at it again. Thanks!

**Comment by ghost** [comment]
This issue will be watched and if it becomes a problem again, we will fix it.
