### ISSUE TITLE
Upgrade refresh

### ISSUE THREAD

**Issue by VishwamR** [thebclickteam/bocracy#205]
Every time I upgrade a character it doesn't show the stat change unless I go to another page and come back

**Comment by ghost** [comment]
Yes this was already resolved in pr #200, and found in issue #194. Again like in issue #193, it may be a cache problem, or because you are using the unpatched iOS app. I will close this issue and mark it as a duplicate.

**Comment by VishwamR** [comment]
When are we going to patch the iOS app?

>

**Comment by ghost** [comment]
Soon after I get a few more things done. I am projecting maybe we should release it on Feb 1st. This is a simple day being the first day, plus it is National Freedom Day in the US (b-Ocracy).

**Comment by VishwamR** [comment]
K

>
