### ISSUE TITLE
Alinar attack animations

### ISSUE THREAD

**Issue by VishwamR** [thebclickteam/bocracy#206]
All the attack animations in alinar went to potato and are the original sword attack animations. I'm not sure if this is a glitch or if it's just unfinished. If it's unfinished is there anything I can do to help.

**Comment by VishwamR** [comment]
All not ask

**Comment by VishwamR** [comment]
Btw it happens if dericil PvP

**Comment by ghost** [comment]
Yes. This is supposed to happen because they were not made yet. You can design them if you want. I will close this issue and mark it as a duplicate of #39 because that is the issue similar to this. Thanks for noticing!
