### ISSUE TITLE
Show back button on game over screens

### ISSUE THREAD

**Issue by stonejess** [thebclickteam/bocracy#207]
Once you win or lose, you have to do another battle then hit a back button in the top corner. It’s so small the most people don’t notice it. When it ends, there should be a button that sends you back, instead of starting a battle to hit the button in the corner.

**Comment by VishwamR** [comment]
Good idea it is kind of annoying when you have to start a battle

>

**Comment by ghost** [comment]
This makes sense. That sounds good. I will patch this in the next release.
