### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by stonejess** [thebclickteam/bocracy#208]
When playing the app, I whent to eora no joke, 9 times! Not say this is a bad thing because I miss the maps and they should be added back.

**Comment by VishwamR** [comment]
I think that's going to be patched in the Feb update

>

**Comment by stonejess** [comment]
Thanks

**Comment by ghost** [comment]
No, @stonejess and @VishwamR, the maps will be added back later after the Feb update.

**Comment by VishwamR** [comment]
Not that the area repeat

**Comment by ghost** [comment]
So you are saying #189?

**Comment by VishwamR** [comment]
Yep

**Comment by ghost** [comment]
Should I mark this as a duplicate and have @stonejess create an issue for adding back the maps ("story mode")?

**Comment by VishwamR** [comment]
Campaign mode

**Comment by VishwamR** [comment]
K but did u get the redesigned maps I sent u

**Comment by ghost** [comment]
Not the latest updated ones.

So @stonejess, you could create an issue for the campaign mode, if you want.

**Comment by stonejess** [comment]
k, sounds good. i have a backstory that might go well with the game

**Comment by ghost** [comment]
We already have a backstory @stonejess by the way. You can read it at https://bocracy.com/story
