### ISSUE TITLE
Campaign mode

### ISSUE THREAD

**Issue by stonejess** [thebclickteam/bocracy#209]
You start off with maps, and before any of the places show, you have to go to a training area. This is where teacher a (or something else) teaches you how to battle. Once you’re done training, one place on the map appears. You have to defeat all of the b’s and the boss to get to the next level. The bosses drop something (🤷🏻‍♂️) that you have to collect to go to the special area to win the game. Finally, throughout the game, you learn about the story of B-ocracy

**Comment by ghost** [comment]
I like calling the tutorial the training area. This training area should be when you start your first battle anywhere (not just campaign mode).

@VishwamR has already created the campaign level paths. These have bosses and battlegrounds that progress.

**Comment by VishwamR** [comment]
Done with dericil

**Comment by ghost** [comment]
Why was this issue closed?

**Comment by VishwamR** [comment]
Campaign mode levels were made not the training levels

**Comment by stonejess** [comment]
This is a copy of #216
