### ISSUE TITLE
Battleground Background Animations

### ISSUE THREAD

**Issue by stonejess** [thebclickteam/bocracy#210]
The animations in the background are really easy to do. You make a stop motion or something else.
Then when the battle starts, the code thinks, when battle starts, play animation.

**Comment by ghost** [comment]
It will not be a stop motion animation, it would be a svg animation. This was talked about in issue #130. It marked it as a duplicate and we will use this issue now.

**Comment by ghost** [comment]
I don't think we need this right now, as we are limiting b-Ocracy development to work on other products. This would require much work also.
