### ISSUE TITLE
Campaign mode 

### ISSUE THREAD

**Issue by stonejess** [thebclickteam/bocracy#216]
At the start of the game, you design your avatar, which you control in the game. you chose standard clothes to start of with. Then the game begins.

You start off in the training camp. The training master teaches you how to battle, and he lets you try out a few battles on your own, where you earn only 100 Redbacks, since the player is just starting off.

Next, you go to to the middle of the island where you find a giant city. you have find a ancient trader to buy a map of B-ocracy  (the old map graphics will be hanging in the background as a little Easter egg)
He sends you on a quest to find a monster who stole a paper from him. when you deliver it back to him, he gives it to you as a reward, along with 100 Redbacks. ( the paper is ripped ) You have to find all of the pieces of the letter which tells you the whole origin of B-ocracy. 

You continue exploring the world, trading with villagers in towns, buying looks for your avatar, and fighting along the way.

Finally, there is a bunch of side quests you can complete for Redbacks.

What do you think @cameronsamuels  @ethanchoo @VishwamR ?

**Comment by ethanchoo** [comment]
I think it sounds pretty interesting! How many pieces of the letter will there be?

**Comment by stonejess** [comment]
One for each zone  we have

**Comment by stonejess** [comment]
That might be too much

**Comment by stonejess** [comment]
Whatever works for you

**Comment by VishwamR** [comment]
We'll have to put that in slowly piece by piece

**Comment by ghost** [comment]
This sounds really great! Here are my thoughts:

### Avatar
This is a wonderful idea. This gives another way people will enjoy playing. It is also a way where there is another thing people can buy with their redbacks. We can add more clothing every update. The avatar can be on the campaign trails moving to the level you select/hover over.

### Training camp
This is another great idea. I like the name. This would be great to do.

### The letters/maps
I like this idea a lot. Maybe, if this is not what you were thinking, we could still use the maps we have designed but it only shows the part of the map you have found. The rest of the map will be hidden. If so, we could design the maps to look more like on paper and not like cartoon graphics on water (ancient paper). This will look more realistic, cool, and fit the story (maps are on paper).

### Quests
This is another great idea. I like the idea of the side quests. You would obviously still battle and go on to higher levels, but the quests add something different. There could be the storyline/"the normal" quests (always the same for everyone, one at a time, and have to do with their progress of the game), and there could be daily quests which could be something different everyday (even if you never finished the previous) and it would be random (not day specific) and it would be something that has nothing to do with the storyline ("earn 200 redbacks", "play 10 battles", etc).

### Villagers, trading, etc
This idea would be cool, but I don't see how this would be practical. b-Ocracy doesn't really have items right now (but we could add them for this, 😄) and I don't see how you would trade (would it be on the trails, would it look like you are in the building, etc). But if we figure something out, maybe it would be cool.

Thanks for your ideas!

**Comment by VishwamR** [comment]
Trade and buy exclusive clothing with villagers?

Also how about achievements

>

**Comment by ghost** [comment]
Achievements sound cool!

Yeah, the villagers can be the clothing trading. Thanks!

**Comment by stonejess** [comment]
there can also be an arena to battle other players

**Comment by VishwamR** [comment]
Good idea

**Comment by ghost** [comment]
This won't be for b-Ocracy. Possibly the prequel, or a remake of b-Ocracy.

A remake sounds neat. Listen to this. b-Ocracy has a stroyline but it isn't in the game. So we could possibly make a game under a different name that has b-Ocracy's missing storyline. This could be the sequel to the prequel and the prequel will be the original. b-Ocracy can still be a side game.

@stonejess, @ethanchoo, @VishwamR
