### ISSUE TITLE
Fix iOS app loading logo

### ISSUE THREAD

**Issue by ghost** [thebclickteam/bocracy#218]
The b-Ocracy loading logo does not work on the iOS app. This needs to be fixed for v2.1.0.

We should also use the new homepage background as the loading logo and not the current loading logo.

**Comment by ghost** [comment]
I found the problem. The logo not showing up is caused by line 3 of `live.js`(on the `master-ios` branch).

The reason for this is because it is referencing the online logo. So whenever the user has no internet (including disabling cellular data usage for the specific app like I did) then the logo doesn't show up (unless if it is already cached).

This needs to be fixed for many reasons:
- The logo obviously won't show up so it will look bad
- It uses WiFi or Cellular Data use (which it promises to not)
- It takes longer to load (plus uses more battery)
- It is referencing another outside data source
- It still has the unused file in the app
- It uses a little bit extra code
- The logo should be updated
And some more.

**Comment by nihalmenon** [comment]
I will resolve this issue
