### ISSUE TITLE
Background music 

### ISSUE THREAD

**Issue by stonejess** [thebclickteam/bocracy#219]
Background music would be a great addition to the game. I have some ideas if we add it.

**Comment by ghost** [comment]
We already have many background songs that we have already created. The only problem is, we removed it because it wouldn't work on iOS due to an iOS update that disabled audio on websites (unless if they were played when something is clicked, which trust me, won't work in this situation).

**Comment by stonejess** [comment]
Ok Thanks!

**Comment by ghost** [comment]
We could possibly add sound the iOS app though through native iOS code and not the embedded website. That will work better than on the embedded website and obviously it will actually play.

We can leave this open. I like the idea.
