### ISSUE TITLE
Replace Byter B in A87 Cannon with the World War A

### ISSUE THREAD

**Issue by stonejess** [thebclickteam/bocracy#221]
A87 Cannon a has a small Byter b at its bace. I think this should be removed or changed because it makes no sense that you are on the a team and playing with a b character.

**Comment by stonejess** [comment]
I’m not trying to change all the hard work you put into this game but I’m just trying to make it better.

**Comment by stonejess** [comment]
Just saying

**Comment by ghost** [comment]
We originally added that Byter B as an easter egg. We can still remove it if you want.

**Comment by stonejess** [comment]
That’s cool. We could add a backstory about how our hero reprogrammed a byter b to be on the a side. (Ktso Easter egg kind of)

**Comment by stonejess** [comment]
You don’t have to delete it

**Comment by VishwamR** [comment]
Wasnt there a traitor a that worked on the opposite side.

>

**Comment by stonejess** [comment]
I don’t know

**Comment by ghost** [comment]
@VishwamR, are you talking about the Rogue B?

**Comment by VishwamR** [comment]
Yee

**Comment by ghost** [comment]
Close this issue?

**Comment by VishwamR** [comment]
No we should change it to maybe a WWII b

**Comment by VishwamR** [comment]
A not b

**Comment by ghost** [comment]
What?

**Comment by VishwamR** [comment]
We should replace the byter b with a ww A

**Comment by ghost** [comment]
In the A87 Cannon? If we do, we can't have the easter egg. Either way, it's fine. I actually would be for your idea, @VishwamR, of changing it to the WW A.

@stonejess, keep the Byter and the easter egg, or change it to the WW A?

**Comment by ghost** [comment]
@stonejess and I have decided to remove the Byter B from the image and replace it with the World War A.

**Comment by ghost** [comment]
I can do this at some point
