### ISSUE TITLE
Iron Dollar (Secondary currency)

### ISSUE THREAD

**Issue by stonejess** [thebclickteam/bocracy#222]
Gems 💎 could be added to the game to make upgrades easier if they don’t have enough Red-backs. Also it opens a chance to add in app purchases and adds to get gems if they need them badly.

**Comment by stonejess** [comment]
We could save the in app purchasing for later if you want

**Comment by VishwamR** [comment]
We have an iron dollar designed

**Comment by ghost** [comment]
@stonejess, like @VishwamR said, the iron dollar will be this second currency.

**Comment by ghost** [comment]
Future game
