### ISSUE TITLE
Make a bullet weapon

### ISSUE THREAD

**Issue by ghost** [thebclickteam/bocracy#3]
Right now, bullets are just `missile` or `shadow_ball`

**Comment by ghost** [comment]
How large are these "bullet" icons? And which characters "use" bullets besides the Sniper B?

**Comment by ghost** [comment]
And I think "missiles" should be for `aircraft` and something similar for any tank-like character

**Comment by ghost** [comment]
@faithtsang 

The `worldwar`, `mecenery`, and more should use a `bullet`.

How big are they? They **must be SVG** format and **3:2 ratio**.

**Comment by CooperLan** [comment]
Done!!!

**Comment by ghost** [comment]
This is sort of a duplicate of #39
