### ISSUE TITLE
Character shadows

### ISSUE THREAD

**Issue by ethanchoo** [thebclickteam/bocracy#50]
This would not apply to all characters, but there could be a capsule shaped shadow under every terrestrial character. This would be an easier addition than if every character had a more detailed shadow (something that could be added later in the game).

**Comment by ghost** [comment]
Great idea. I might be able to use CSS shadows if we start using SVG's for the characters (which we should do but will take some time to adjust).

So like you said, simple shadows could possibly work.

**Comment by ethanchoo** [comment]
I posted an example of this on slack

**Comment by ghost** [comment]
Shadows would be a great idea. Perhaps you could do it for the aerial characters as well? It makes a lot of sense since shadows are more evidently cast from higher up than just on ground. But of course, terrestrial characters first.

**Comment by ghost** [comment]
I have done some commits on this issue in [thebclickteam:battle-shadows](https://github.com/thebclickteam/bocracy/tree/battle-shadows) and it is for all the characters.

All I need to do are some fixes and lowering certain character images.

**Comment by ghost** [comment]
I now agree that we should put the shadows in the actual image because the code isn't working the best and will take up too much code. Plus, @ethanchoo said to only have a shadow on certain characters.

**Comment by ethanchoo** [comment]
But on a realistic approach, you would want to make the shadow different in each one, because the light source (the sun) would give each character different shadows. For example, the setting of the city in the night would give the characters light shadow, while Alief would give the characters a dark shadow.

**Comment by ghost** [comment]
Yeah, I see your approach @ethanchoo, the only problem is that this would be more complex. We can see what we can do.

**Comment by ethanchoo** [comment]
You can do it the easier way, but the realistic way would be a bonus

**Comment by ghost** [comment]
We can definitely do the simple way now, @ethanchoo. All you have to do is add the shadows to the character images and submit the update of the image.

Once we have time, we can add the more realistic way.

**Comment by ghost** [comment]
This is a great idea (making shadows) but @ethanchoo and I have thought of an idea to only put them in the actual image and not in the code. Because of this, I will close this issue, and we can continue to add shadows to all of the characters.
