### ISSUE TITLE
Endless mode not working

### ISSUE THREAD

**Issue by CooperLan** [thebclickteam/bocracy#64]
In endless it says webpage not available when you click play and it steals your readbacks

**Comment by ghost** [comment]
1. What app are you using (online, Android, etc).
2. Does the big “Play” button work?

**Comment by ghost** [comment]
I have found this is for the Android app.

Please create an issue [here](https://github.com/thebclickteam/bocracy.android/issues/new) for the Android app issues instead of b-Ocracy's general issues.

**Comment by CooperLan** [comment]
The phone you gave me

**Comment by ghost** [comment]
The big play button isn't showing up for me. It just might be a temporary thing though.

**Comment by ghost** [comment]
The button at the top that is bigger & wider than the rest in [index.html](https://bocracy.com/b/index.html) is the “big play button”.

**Comment by ghost** [comment]
All this is resolved with removing the Android app like previously discussed with executives.
