### ISSUE TITLE
Add Google Play Games achievements

### ISSUE THREAD

**Issue by CooperLan** [thebclickteam/bocracy#67]
Need to add achevements for play games.

**Comment by ghost** [comment]
This is a really good feature to add, but there is one problem stopping us from doing this.

We basically just have the game shown in a “WebView” which basically shows a website. That means that the content in the webview (basically everything) can’t interact with native elements, including the webview itself, in-app purchases, and in your case, Google Play Games achievements and leaderboards.

So, if we transition all of our infrastructure into using PhoneGap or Apache Cardova, we will be able to do this. But first, I need to get more farmiliar with those frameworks.

**Comment by CooperLan** [comment]
Im aready fimilar with google play stuff

**Comment by ghost** [comment]
I meant the developing of it and the other frameworks (PhoneGap and Cordova) need to be learned and used.

**Comment by ghost** [comment]
I am going to close this issue and label it with “on hold” and “future” and will reopen it once we use Cordova.

**Comment by ghost** [comment]
This is a good idea, but I don't think it will be good for b-Ocracy. Maybe for another game.
