### ISSUE TITLE
Alligator gar school replacement

### ISSUE THREAD

**Issue by ethanchoo** [thebclickteam/bocracy#70]
Replace the alligator gar school with a ichthyosaur B.

**Comment by ghost** [comment]
@ethanchoo, send me the ichthyosaur assembly file and I will add it to the game.

**Comment by ghost** [comment]
Thanks, I will add it now.

**Comment by ghost** [comment]
I just added it to the lib in commit [02f7db8](https://github.com/thebclickteam/lib/commit/02f7db8866dd884958a56999533e4b12c8770de8)
