### ISSUE TITLE
Store Redesign

### ISSUE THREAD

**Issue by ghost** [thebclickteam/bocracy#71]
@ethanchoo an I have thought of a perfect idea of a new layout for the store. Please comment with the layout image.

This is really good and should be done.

**Comment by ethanchoo** [comment]
Here is the idea:

![store image dummy](https://user-images.githubusercontent.com/30300679/30086768-846fed0e-9262-11e7-82c1-99b09c769191.PNG)

**Comment by ghost** [comment]
@ethanchoo, can you send me the healing and health icons in the store layout idea image (as assembly files). I will work on this issue right now.

**Comment by ghost** [comment]
Great work Ethan! The store design looks great!

**Comment by stonejess** [comment]
Looks perfect
