### ISSUE TITLE
Add sun shadow to Alief background

### ISSUE THREAD

**Issue by ethanchoo** [thebclickteam/bocracy#74]
The sun at Alief plains does not have a yellow shadow like it originally had.

**Comment by ghost** [comment]
That is because it is a SVG instead of a PNG. I can look into adding the shadow.

**Comment by ethanchoo** [comment]
Couldn't it be saved as an SVG from Assembly?

**Comment by ghost** [comment]
I did save it from assembly but it removed the shadow.
